
apiVersion: v1
kind: Namespace
metadata:
  name: staging

apiVersion: v1
kind: Namespace
metadata:
  name: production


apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: staging

apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  namespace: staging

apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-sa
  namespace: staging