apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: staging
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'devops-assignment'
        static_configs:
          - targets: ['api-gateway:8000', 'orders-service:8000', 'inventory-service:8000']
